version: "3.9"

services:

  db:
    image: mariadb:11
    container_name: cert_base_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cert_db
      MYSQL_USER: fakir
      MYSQL_PASSWORD: Ytrhjvfyn16!!!
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: cert_base_app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: fakir
      DB_PASSWORD: Ytrhjvfyn16!!!
      DB_NAME: cert_db
      SECRET_KEY: change_this_super_secret_key
    ports:
      - "58888:5000"

volumes:
  db_data: