"""added table certificatetemplate

Revision ID: 088230941e04
Revises: cf4c278d5a41
Create Date: 2026-07-22 09:19:24.326361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088230941e04'
down_revision = 'cf4c278d5a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('folder_path', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_count', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_services', schema=None) as batch_op:
        batch_op.drop_column('service_count')

    op.drop_table('certificate_templates')
    # ### end Alembic commands ###
