"""permission.resourse_id: nullable = true

Revision ID: 250697c82b3a
Revises: 6596ac98a06b
Create Date: 2026-03-17 14:36:59.114481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '250697c82b3a'
down_revision = '6596ac98a06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('resource_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('resource_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
