"""certificate table expand

Revision ID: 3e6a83ba68a7
Revises: a835fe529da3
Create Date: 2026-06-15 17:05:02.085972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e6a83ba68a7'
down_revision = 'a835fe529da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mol_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expiration_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('spending_client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('spending_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('template_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('require_original', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('require_stamp', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_single_use', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('max_50_percent', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deactivate_reason', sa.String(length=100), nullable=True))
        batch_op.alter_column('reason',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['mol_id'], ['id'])
        batch_op.create_foreign_key(None, 'clients', ['spending_client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('reason',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('deactivate_reason')
        batch_op.drop_column('max_50_percent')
        batch_op.drop_column('is_single_use')
        batch_op.drop_column('require_stamp')
        batch_op.drop_column('require_original')
        batch_op.drop_column('template_path')
        batch_op.drop_column('spending_type')
        batch_op.drop_column('spending_client_id')
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('mol_id')

    # ### end Alembic commands ###
