"""added place to users, login=unique

Revision ID: 4695dac2db96
Revises: 52ed1fafc742
Create Date: 2026-06-18 12:34:29.669549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4695dac2db96'
down_revision = '52ed1fafc742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['login'])
        batch_op.create_foreign_key(None, 'places', ['place_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('place_id')

    # ### end Alembic commands ###
