"""adding issuing_place to certificate

Revision ID: 52ed1fafc742
Revises: 3e6a83ba68a7
Create Date: 2026-06-16 12:32:35.419950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ed1fafc742'
down_revision = '3e6a83ba68a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_place_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'places', ['issue_place_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('issue_place_id')

    # ### end Alembic commands ###
