"""add table servicegroup

Revision ID: 5d603d996b03
Revises: d360d9515d8e
Create Date: 2026-03-19 11:04:23.126415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d603d996b03'
down_revision = 'd360d9515d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicegroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicegroup_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'servicegroup', ['servicegroup_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('servicegroup_id')

    op.drop_table('servicegroup')
    # ### end Alembic commands ###
