"""users.group_id: nullable = true

Revision ID: 6596ac98a06b
Revises: a4c1da4b656f
Create Date: 2026-03-17 13:25:45.514103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6596ac98a06b'
down_revision = 'a4c1da4b656f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
