"""added timestampmixin

Revision ID: 6624dec4705e
Revises: da7be45a37c2
Create Date: 2026-07-24 11:09:45.167192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6624dec4705e'
down_revision = 'da7be45a37c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('certificate_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('certificate_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('certificate_template_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('certificate_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('certificate_transaction_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('certificate_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_certificate_transactions_created_at'))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('certificate_usages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('group_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('servicegroup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('edit_date')

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('servicegroup', schema=None) as batch_op:
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('group_permissions', schema=None) as batch_op:
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('certificate_usages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('certificate_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=False))
        batch_op.create_index(batch_op.f('ix_certificate_transactions_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('certificate_transaction_items', schema=None) as batch_op:
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('certificate_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('certificate_template_links', schema=None) as batch_op:
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('certificate_services', schema=None) as batch_op:
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('certificate_series', schema=None) as batch_op:
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('edit_date')
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
