"""add max_number in certificateseries

Revision ID: 6de0d15e321e
Revises: 71513862cebf
Create Date: 2026-07-09 14:39:30.119956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de0d15e321e'
down_revision = '71513862cebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_series', schema=None) as batch_op:
        batch_op.drop_column('max_number')

    # ### end Alembic commands ###
