"""creating table certificateseries for non-number certificates, certificates.number = true

Revision ID: 71513862cebf
Revises: 621cd52e1ef2
Create Date: 2026-07-09 10:49:24.393294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71513862cebf'
down_revision = '621cd52e1ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=20), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False, server_default="0"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    op.drop_table('certificate_series')
    # ### end Alembic commands ###
