"""certificate lifecycle fields

Revision ID: 74913b13fbc8
Revises: 4bd463e4c7ae
Create Date: 2026-04-24 10:35:51.170199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74913b13fbc8'
down_revision = '4bd463e4c7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['edit_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('edit_user_id')
        batch_op.drop_column('edit_date')

    # ### end Alembic commands ###
