"""increase note size

Revision ID: 9869c14901d9
Revises: 99280acc12fd
Create Date: 2026-06-09 16:26:36.552652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9869c14901d9'
down_revision = '99280acc12fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=True)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=True)

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=True)

    with op.batch_alter_table('servicegroup', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('servicegroup', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
