"""add unique constraint for certificate series and number

Revision ID: 99280acc12fd
Revises: 525fef2e32f8
Create Date: 2026-06-09 15:39:30.405953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99280acc12fd'
down_revision = '525fef2e32f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_certificate_series_number', ['series', 'number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint('uq_certificate_series_number', type_='unique')

    # ### end Alembic commands ###
