"""expand client structure

Revision ID: a835fe529da3
Revises: 9869c14901d9
Create Date: 2026-06-10 14:51:18.253782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a835fe529da3'
down_revision = '9869c14901d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastName', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('firstName', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('secondName', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('externalId', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('externalId')
        batch_op.drop_column('email')
        batch_op.drop_column('secondName')
        batch_op.drop_column('firstName')
        batch_op.drop_column('lastName')

    # ### end Alembic commands ###
