""" add unique to certificatetemplatelinks

Revision ID: d2e33745b452
Revises: e9678ac54c6c
Create Date: 2026-07-27 15:08:44.790382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e33745b452'
down_revision = 'e9678ac54c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_template_links', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_certificate_template_version', ['certificate_id', 'template_version_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_template_links', schema=None) as batch_op:
        batch_op.drop_constraint('uq_certificate_template_version', type_='unique')

    # ### end Alembic commands ###
