"""changed column for template_versions

Revision ID: e9678ac54c6c
Revises: 6624dec4705e
Create Date: 2026-07-24 14:23:20.365457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9678ac54c6c'
down_revision = '6624dec4705e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_path', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.drop_column('original_filename')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', mysql.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('original_filename', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('filename')
        batch_op.drop_column('folder_path')

    # ### end Alembic commands ###
