"""added new tables: services, certificatetransaction, certificatetransactionitems

Revision ID: f9fb0b3ed9df
Revises: 6de0d15e321e
Create Date: 2026-07-13 10:07:27.686014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fb0b3ed9df'
down_revision = '6de0d15e321e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('servicegroup_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mis_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['servicegroup_id'], ['servicegroup.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('mis_id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_servicegroup_id'), ['servicegroup_id'], unique=False)

    op.create_table('certificate_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_transactions_certificate_id'), ['certificate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_transactions_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_transactions_created_at'), ['created_at'], unique=False)

    op.create_table('certificate_transaction_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=250), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['certificate_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate_transaction_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_transaction_items_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_transaction_items_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_transaction_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_transaction_items_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_transaction_items_service_id'))

    op.drop_table('certificate_transaction_items')
    with op.batch_alter_table('certificate_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_certificate_transactions_client_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_transactions_certificate_id'))

    op.drop_table('certificate_transactions')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_servicegroup_id'))
        batch_op.drop_index(batch_op.f('ix_services_is_active'))

    op.drop_table('services')
    # ### end Alembic commands ###
